# Generated by Django 2.2 on 2021-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_option',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='price_add_plus',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_add_pro',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_basic',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
