# Generated by Django 2.2 on 2021-08-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_auto_20210815_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_add_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_add_pro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
