# Generated by Django 2.2 on 2021-08-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0003_auto_20210815_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_qty',
            field=models.IntegerField(null=True),
        ),
    ]
