# Generated by Django 2.2 on 2021-08-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('quote_app', '0005_remove_item_max_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='added_item',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='login_reg_app.CUSTOMER'),
        ),
        migrations.AlterField(
            model_name='added_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_line_items', to='quote_app.ITEM'),
        ),
    ]
