# Generated by Django 2.2 on 2021-08-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0007_auto_20210821_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=95, null=True),
        ),
    ]
