# Generated by Django 2.2 on 2021-08-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0009_auto_20210821_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='RECEIPT',
        ),
    ]
